### ISSUE TITLE
Doesn't compile `<style jsx>` when rendering multiple components per file

### ISSUE THREAD

**Issue by jacobmischka** [zeit/styled-jsx#12]
After pulling from master, working around #11, and linking, babel still doesn't seem to compile the tag. Babel is running without any complaints.

### styled-jsx
![image](https://cloud.githubusercontent.com/assets/3939997/20894156/f419c5e6-bad9-11e6-833e-c55e182f9979.png)

### .babelrc in project
```
{
	"presets": [
		"react",
		["es2015", { "modules": false }]
	],
	"plugins": [
		"array-includes",
		"styled-jsx/dist/babel"
	]
}
```

### React complaining about `jsx` prop
![image](https://cloud.githubusercontent.com/assets/3939997/20894225/2fc1864c-bada-11e6-8545-40721dbd87b9.png)

**Comment by leo** [comment]
@jacobmischka Does 0.0.3 work?

**Comment by jacobmischka** [comment]
It does not seem to.

Here's where I'm using it: https://gist.github.com/ebc481015aa80af18efc38465fcb8657

babelrc:
```
{
	"presets": [
		"react",
		["es2015", { "modules": false }]
	],
	"plugins": [
		"array-includes",
		"styled-jsx/babel"
	]
}
```

![image](https://cloud.githubusercontent.com/assets/3939997/20895013/5334a048-badd-11e6-834f-39977c6f706f.png)

**Comment by jacobmischka** [comment]
Actually sorry, here's my repo: https://github.com/jacobmischka/ics-merger/tree/styled-jsx

**Comment by jacobmischka** [comment]
Oh sorry, you'll need a `.env.json` file to run it. Here's mine: https://gist.github.com/6eebe8873893ae6d7ac2f3ad64aa7737

**Comment by jacobmischka** [comment]
I'll try to create a minimum reproducible repo at some point later today when I get a few minutes, thank you!

**Comment by adamyonk** [comment]
I'm seeing something similar, and it seems like my `<style jsx>` are just getting dumped into the page unparsed, and therefore as global style rules:
<img width="281" alt="screen shot 2016-12-05 at 4 24 13 pm" src="https://cloud.githubusercontent.com/assets/33258/20902915/5629452c-bb07-11e6-987a-92a311b1d5f4.png">
<img width="788" alt="screen shot 2016-12-05 at 4 25 06 pm" src="https://cloud.githubusercontent.com/assets/33258/20902941/6b7855d0-bb07-11e6-9df9-fa3b1e991220.png">

**Comment by jacobmischka** [comment]
Oh you're right, it's doing that for me too. I didn't even check, I just assumed it failed because of the errors.

**Comment by treshugart** [comment]
I can confirm this is happening for me, as well. If I run `babel` from the CLI with only this as the plugin, nothing is transformed:

```sh
tshugart:skate-styled-jsx tshugart$ babel src/index.js --plugins styled-jsx/babel
tshugart:skate-styled-jsx tshugart$ babel src/index.js --plugins styled-jsx/babel
/** @jsx h */

import 'skatejs-web-components';
import { Component, define, h } from 'skatejs';

const Test = define('x-test', class extends Component {
  renderCallback() {
    return <p><slot /></p>;
  }
});

window.customElements.define('x-app', class extends Component {
  renderCallback() {
    return <div>
        <p>this should be bold</p>
        <Test>this should not be</Test>
        <style jsx>{'p { font-weight: bold }'}</style>
      </div>;
  }
});
```

I'm assuming, that at the very least, the `<style jsx>` part should be transpiled? I tried placing the `transform-react-jsx` plugin before *and* after with no luck.

**Comment by sergiodxa** [comment]
I have the this bug too, I added:

```json
"plugins": [
  "styled-jsx/babel"
]
```

To my `.babelrc` and in a component:

```jsx
<style jsx>{`
  article {
    color: blue;
  }
`}</style>
```

And React is adding the `<style>` tag and complaining about the `jsx` unknown prop.

**Comment by hzoo** [comment]
everyone should try styled-jsx@0.0.5 which should fix it

**Comment by treshugart** [comment]
@hzoo still seems to be an issue with 0.0.5. Is there something we're doing wrong? My `.babelrc` is just:

```json
{
  "plugins": ["styled-jsx/babel"]
}
```

And I still get:

```sh
tshugart:skate-styled-jsx tshugart$ babel src/index.js 
/** @jsx h */

import 'skatejs-web-components';
import { Component, define, h } from 'skatejs';

const Test = define('x-test', class extends Component {
  renderCallback() {
    return <p><slot /></p>;
  }
});

window.customElements.define('x-app', class extends Component {
  renderCallback() {
    return <div>
        <p>this should be bold</p>
        <Test>this should not be</Test>
        <style jsx>{'p { font-weight: bold }'}</style>
      </div>;
  }
});
```

**Comment by jacobmischka** [comment]
Unfortunately it seems to still be happening to me 
![image](https://cloud.githubusercontent.com/assets/3939997/20950077/0739423c-bbe3-11e6-81fc-3744383221b5.png)

`styled-jsx` seems to be called, I added a log to `styled-jsx/babel.js` and it's showing up in the output. But I'm still getting the error.

![image](https://cloud.githubusercontent.com/assets/3939997/20950181/cfca9462-bbe3-11e6-8724-e4727b70fc1f.png)

```
yarn build:webpack v0.18.0
$ webpack -p 
running babel
Hash: afc2d2da1570a962ac31
Version: webpack 2.1.0-beta.27
Time: 12225ms
        Asset     Size  Chunks             Chunk Names
    bundle.js   797 kB       0  [emitted]  main
bundle.js.map  6.14 MB       0  [emitted]  main
 [675] multi main 88 bytes {0} [built]
    + 675 hidden modules

Webpack Bundle Analyzer saved stats file to /home/mischka/projects/ics-merger/public/js/stats.json
Done in 13.13s.

```

Please let me know if there's anything I can do to help, thanks!

**Comment by sergiodxa** [comment]
Now I have the error described in #16

**Comment by adamyonk** [comment]
I can confirm that 0.0.5 does not resolve the issue I am having. Let me know if I can give more information to troubleshoot this somehow!

**Comment by jacobmischka** [comment]
The tag is now compiling for me with 0.0.7, though I seem to be running into a different issue now. Regardless, if someone else confirms that I'll close the issue. Thanks everyone!

**Comment by adamyonk** [comment]
@jacobmischka @hzoo 0.0.7 fixed this issue for me as well.

**Comment by treshugart** [comment]
Okay, so it seems to work only under specific conditions.

This transpiles:

```js
/** @jsx h */

import 'skatejs-web-components';
import { Component, define, h } from 'skatejs';

define(class Test extends Component {
  renderCallback () {
    // return <p><span /></p>;
  }
});

window.customElements.define('x-app', class extends Component {
  renderCallback () {
    return (
      <div>
        <p>this should be bold</p>
        <Test>this should not be</Test>
        <style jsx>{`p { font-weight: bold }`}</style>
      </div>
    );
  }
});
```

It seems if I comment out the following line, it works:

```js
return <p><span /></p>;
```

Moving the component to a separate file works.

**Comment by aputinski** [comment]
Having the same issue. If a file contains two component definitions and the bottom one renders a `<style jsx>` component, no transformation happens. Removing the top component definition fixes the issue.

**Comment by jacobmischka** [comment]
That seems like a different problem than the one this issue was originally referring to, despite the title still fitting. I think it would be best if a new issue was created, but I will keep this one open until that happens.

**Comment by jacobmischka** [comment]
Ah never mind I can just change the title

**Comment by aputinski** [comment]
Here's are my test cases:

**DOES NOT** get transformed (style tag only in last component)
```jsx
import React from 'react'

const ComponentLink = () =>
  <li>
    <span>Hello</span>
  </li>

const App = () =>
  <ul>
    <ComponentLink />
    <style jsx>{`span { color: blue; }`}</style>
  </ul>

export default App
```

**DOES** get transformed (style tag only in first component)
```jsx
import React from 'react'

const ComponentLink = () =>
  <li>
    <span>Hello</span>
    <style jsx>{`span { color: blue; }`}</style>
  </li>

const App = () =>
  <ul>
    <ComponentLink />
  </ul>

export default App
```

**DOES** get transformed (style tag in both components)
```jsx
import React from 'react'

const ComponentLink = () =>
  <li>
    <span>Hello</span>
    <style jsx>{`span { color: blue; }`}</style>
  </li>

const App = () =>
  <ul>
    <ComponentLink />
    <style jsx>{`span { color: red; }`}</style>
  </ul>

export default App
```

**Comment by jacobmischka** [comment]
What about this case, with only in second component, but being rendered after the style tag in the second?

```
import React from 'react'

const ComponentLink = () =>
  <li>
    <span>Hello</span>
  </li>

const App = () =>
  <ul>
    <style jsx>{`span { color: blue; }`}</style>
    <ComponentLink />
  </ul>

export default App
```

**Comment by schnerd** [comment]
^ building off of aputinski's test cases, a temporary workaround for this issue is to just put an empty style tag in each component in the file:

```
import React from 'react'

const ComponentLink = () =>
  <li>
    <span>Hello</span>
    <style jsx>{''}</style>
  </li>

const App = () =>
  <ul>
    <ComponentLink />
    <style jsx>{`span { color: red; }`}</style>
  </ul>

export default App
```

**Comment by giuseppeg** [comment]
The problem is that the babel plugin works only on the first JSX block it encounters.
If it doesn't find any styles it skips the rest.

@rauchg I have a fix for this however it won't transpile ["jsx partials"](https://github.com/zeit/styled-jsx/issues/1#issuecomment-264925743) – in order to support them we'd need to rethink about the architecture of the plugin since there are a lot of possible scenarios.

With the fix you'd get this:

```jsx
import _JSXStyle from "styled-jsx/style";

const foo = <span>hey</span>
const MyComponent = () => (
  <div data-jsx={"2742264064"}>
      {foo}
      <_JSXStyle css={"span[data-jsx=\"2742264064\"] {color: red;}"} data-jsx={"2742264064"} />
  </div>
)
```

i.e. `foo` won't get the data attribute.

I argue that fixing it partially could be worse than the status-quo but I'd be happy to put a PR together anyway if you think that this is better than nothing.

**Comment by rauchg** [comment]
@giuseppeg not sure I'm too concerned about jsx partials for now. For jsx partials one can use a different `<style jsx>` tag (think different sub-component), or find a way to fit it in the same block somehow.

**Comment by giuseppeg** [comment]
@rauchg ok then shall I put together a PR to fix this issue?

**Comment by rauchg** [comment]
Yes please. This issue definitely needs immediate attention

**Comment by rauchg** [comment]
Released in `0.1.3`

**Comment by katopz** [comment]
Hm, I still seeing this issue. by using https://github.com/zeit/next.js/wiki/Redux-example
and replace `render` in `pages/index.js` with ...

```js
  render () {
    return (
      <Provider store={this.store}>
        <div>
          <Clock/>
          <dl className="foo">
            <style jsx>{`
              .foo {
                font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
                color: red;
              }
              `}
            </style>
            bar
          </dl>
        </div>
      </Provider>
    )
  }
```
I'll get
![screen shot 2016-12-20 at 23 27 53](https://cloud.githubusercontent.com/assets/97060/21358667/0218fbd8-c70c-11e6-9542-6b15e61b6f60.png)

The weird part is if I make file dirty (hit space bar or something) and save to trigger rebuild.
It'll work perfectly after that but if I hit refresh button it will error again.

Maybe I doing things wrong? Do I need `.babelrc`?

Thanks

**Comment by giuseppeg** [comment]
@katopz yes you need a `.babelrc` file at the root of your project or similar. See the [usage](https://github.com/zeit/styled-jsx#usage) section. If the issue persists you may want to join [zeit.chat](https://zeit.chat)

**Comment by ehtb** [comment]
I had to add `plugins: ['styled-jsx/babel']` to my babel loader query config as well.
