### ISSUE TITLE
Cannot find module 'styled-jsx/css'

### ISSUE THREAD

**Issue by Nipher** [zeit/styled-jsx#308]
Hello everyone, thanks for the great project and all the work you guys are doing at Zeit, incredibly awesome work.

I'm having a weird problem when trying to import `styled-jsx/css`.

I see that you [have specs for it](https://github.com/zeit/styled-jsx/blob/master/test/fixtures/styles.js) so I think it's extremely unlikely to be a problem with the project itself.

But I decide to open the issue anyway in case I'm missing something...

I'm using `"styled-jsx": "2.0.2"`, things that I tried without success: 
- Importing it on my project with NextJs
- Adding `styled-jsx` as my project dependency
- Creating an empty project, adding `styled-jsx` as dependency, and trying to simply `require('styled-jsx/css')`
- Using the same node version as you [use on travis](https://travis-ci.org/zeit/styled-jsx/jobs/286211825#L430)
- Cloning the project + yarn link + simply requiring it

All of them using `2.0.2` and with the same outcome: `Cannot find module 'styled-jsx/css'`.

Any thoughts? I hope it's not something stupid from my side 😓💭

**Comment by Mensae** [comment]
Still the same for me. [see](https://github.com/zeit/styled-jsx/issues/302)

**Comment by giuseppeg** [comment]
@Nipher styled-jsx 2.0 is integrated only in Next.js v4, if you have a project that is using v3 there is no way to use a different version of styled-jsx

**Comment by giuseppeg** [comment]
also make sure that you clean any cache:
```
rm -rf node_modules/.cache .next
```

**Comment by Nipher** [comment]
Hey @giuseppeg, thanks for the fast reply, I'm using the `"next": "beta"` actually, does it work with the beta?

Also I created a project only with `styled-jsx`, all stand alone, without nextjs, with no luck.

I tried removing`node_modules/.cache` in my node_modules, but I had no luck 😕 
In the meantime I managed to use pure template literals and not use `styled-jsx/css`, but I would love to use it instead.

**Comment by giuseppeg** [comment]
I think some of the latest beta version ships with v2. `styled-jsx/css` is a fake import to detect css files/blocks internally the plugin eventually removes it. So if you are getting an error chances are that the plugin is not running at all.

**Comment by rgbkrk** [comment]
I've done the same, starting up a brand new app with `next@4.0.3`, `styled-jsx@`, using _just_ the sample given in the README:

```
/* styles.js */
import css from 'styled-jsx/css'

export const button = css`button { color: hotpink; }`
export default css`div { color: green; }`
```

```
This dependency was not found:

* styled-jsx/css in ./styles/index.js
```

**Comment by giuseppeg** [comment]
alright folks I need a test case repo to debug this issue

**Comment by timneutkens** [comment]
@rgbkrk I've tried your case and can't reproduce 🤔

**Comment by bukinoshita** [comment]
I'm having this issue too.

IIRC this is caused because there's no `css.js` file in the root of the project like [this](https://github.com/zeit/styled-jsx/blob/master/style.js), but as @giuseppeg mentioned "_styled-jsx/css is a fake import to detect css_" so I don't know how to fix it.

**Comment by jad11v** [comment]
also having the issue. I couldn't reproduce from the sample repo, but is verified not working in a project i upgraded from next 3

**Comment by Nipher** [comment]
Just created a [NextJs simple test repository](https://github.com/Nipher/test-styled-jsx-css) from scratch (using next@4.1.0 + styled-jsx@2.1.1) and it worked with a very quick and simple example! 👍 

I'll upgrade my project to use 4.1.0 🙇 
I wonder how this fake path works though, I'll look into it later for curiosity 🤔 

Thank you for your time guys, I hope everyone else can also make it work with the same versions that I'm using on the test rep 😕 

I would close the issue but not sure if you guys would like to check if everyone else managed to get it working fine, I didn't test with the same version as @rgbkrk though, not sure if it should be working there also.

**Comment by bukinoshita** [comment]
In my case it still does not work, I'm not using `next.js` so can't upgrade it. Would be good to re-open this issue if possible.

Here's the project that fails: https://github.com/bukinoshita/pilot-component/tree/add/external-css

**Comment by giuseppeg** [comment]
@bukinoshita you are importing ‘next/css’ in styles.js it shoukd be ‘styled-jsx/css’ instead

**Comment by bukinoshita** [comment]
@giuseppeg you are right, my bad.  I had that fixed tho and still gives me the error

```
ERROR in ./src/styles.js
Module not found: Error: Can't resolve 'styled-jsx/css' in
```

**Comment by bukinoshita** [comment]
Can we reopen @giuseppeg ??

**Comment by giuseppeg** [comment]
@bukinoshita chances are that webpack or something else tries to load files/resolve imports before transpiling them with babel. Check your build pipeline

**Comment by Hedgepig** [comment]
I'm having the same issue with `2.2.0` in a Meteor project

**Comment by giuseppeg** [comment]
gonna release v2.2.1 today which should fix this

**Comment by giuseppeg** [comment]
published

**Comment by nfantone** [comment]
@giuseppeg Still experiencing this several month later. Using:

```js
import css from 'styled-jsx/css';

export const global = css.global`
  html {
    font-size: 16px;
  }
  body {
    padding: 0;
  }
`;
```

Gets me:

```sh
Uncaught ReferenceError: css is not defined
```

Using Webpack `4.6.0` + Babel `7.0.0-beta.46`.

**Comment by nfantone** [comment]
@giuseppeg Ok, found out that this feature is still to be released. My bad.

Still, it's rather confusing to see "docs for v3" instructing you to [install module](https://github.com/zeit/styled-jsx#getting-started) using `npm install --save styled-jsx`, which *won't get you the module you're documenting*.

**Comment by giuseppeg** [comment]
@nfantone yeah sorry about that

**Comment by nfantone** [comment]
@giuseppeg Even if not using `css.global` I can't make the "fake" import to work properly with `jest`. Every time I run tests, I get:

```sh
  ● Test suite failed to run

    ReferenceError: css is not defined

      1 | import css from 'styled-jsx/css';
      2 |
    > 3 | console.log(css);
```

My Babel config already includes `"styled-jsx/babel"` and it works fine when _building_ the application. But the `jest` runner doesn't seem to be liking it or it's conflicting in some way.

Any ideas?

**Comment by giuseppeg** [comment]
what is your setup like?

**Comment by nfantone** [comment]
@giuseppeg Looks something like the following:

- React toolkit library built with Rollup.
- `styled-jsx` `2.2.7`
- Using Babel `7.0.0-beta.46`, with `.babelrc` below:

```json
{
    "presets": [
      "react-app"
    ],
    "plugins": [
      "styled-jsx/babel"
    ]
}
```

- Running `jest` + `babel-jest` (both `^23.4.0`).
- Slightly simplified CRA standard Jest configuration.

```json
{
  "jest": {
    "verbose": true,
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "babel-jest",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/file-transform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "setupFiles": [
      "<rootDir>/polyfills.js"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/enzyme.config.js",
    "testEnvironment": "node",
    "moduleNameMapper": {
      "\\.css$": "identity-obj-proxy"
    }
  }
}
```

My suspicion is that `jest` does not know about `styled-jsx/babel` or is not being picked up.

**Comment by giuseppeg** [comment]
@nfantone have you tried to transpile a colocated style tag:

```jsx
() => {
  return <div>hi<style jsx>{`div { color: red }`}</style></div>
}
```

Is that one transpiled? I can take a look if you put together a sample minimal repo.

**Comment by nfantone** [comment]
@giuseppeg Yes, inline styles work as expected. The offending part is the "fake" `css` import.

I managed to put together a reproducible case. And even though it's doesn't _exactly_ match my setup and doesn't output the same error, it does lead to the same behavior. I think this deserves an issue of its own. I'll open one now.

**Comment by nfantone** [comment]
@giuseppeg Sorry for the delay on this. Here: https://github.com/zeit/styled-jsx/issues/469 - I've opened a new issue with a description of reproducible case so we can better track the problem down.
