### ISSUE TITLE
Using styled jsx tag in a React.Fragment breaks zeit/next's HMR

### ISSUE THREAD

**Issue by MrToph** [zeit/styled-jsx#425]
## Expected Behavior
Editing `stlye jsx` styles resting in `React.Fragment` should work with `next`'s HMR, espcially as `next` ships with `styled-jsx` per default.

## Current Behavior
When I put a `style jsx` tag into a `React.Fragment` and change a `style jsx` css property, the page reloads with HMR, but then I get the error:
```
StyleSheetRegistry: styleId: `jsx-1655195659` not found.
Error: StyleSheetRegistry: styleId: `jsx-1655195659` not found.
    at invariant (http://localhost:3000/_next/-/page/index.js:47200:11)
```

```jsx
export default class Canvas extends React.Component {
    render() {
        return (
            <React.Fragment>
                <div className="canvas" />
                <style jsx>{`
                    .canvas {
                        position: relative;
                        height: 100vh;
                        background-color:#123;
                    }
                `}</style>
            </React.Fragment>
        )
    }
}
```

When I replace `React.Fragment` with `div` it works fine

## Steps to Reproduce (for bugs)
I started with the [with-styled-jsx-scss](https://github.com/zeit/next.js/tree/canary/examples/with-styled-jsx-scss): `npx create-next-app --example with-styled-jsx-scss with-styled-jsx-scss-app`
1. Clone this [minimal reproduction](https://github.com/MrToph/next-error).
2. `yarn install`, `yarn run dev`
3. Go to `localhost:3000`
4. Change the CSS rule `background-color` in `src/components/Canvas.jsx`
5. See it breaking

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     v5.0.0 |
| node    |      v8.10   |
| OS      |      Windows 10  |
| browser |      Latest Chrome   |

**Comment by MrToph** [comment]
Is there currently a workaround for this? I don't want to create a wrapper `div` just so I can style my component.

**Comment by giuseppeg** [comment]
This might not be an issue with styled-jsx but with HMR, maybe due to how re-rendering happens with Fragments and the fact that the elements (div and style tags) are siblings.

In reality it seems that the issue is that with HMR the `shouldComponentUpdate` for the `style` tag is never called, I don't know why.

I tried to change the `background-color` and I got the error, but the if you try to change it again, the error page is unmounted and the app re-rendered correctly (i.e. it works).

For what is worth, looking at your example you could just nest the styles inside of the `.canvas` div. Obviously this won't work when you have self closing tags like `img` or `input`.

**Comment by giuseppeg** [comment]
@timneutkens probably you have more experience with HMR ^

**Comment by jaydenseric** [comment]
Same issue, but the error I see is:

```
Warning: Received `true` for a non-boolean attribute `jsx`.

If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.
```

**Comment by giuseppeg** [comment]
@jaydenseric usually that means that you component was not transpiled at all

**Comment by Negan1911** [comment]
I'm getting the same issue but without a `React.Fragment` tag, just using the exact one from the example:
```js
import React from 'react'

export default () => (
  <div>
    Hello world
    <p>scoped!</p>
    <style jsx>{`
      p {
        color: blue;
      }
      div {
        background: gray;
      }
      @media (max-width: 600px) {
        div {
          background: blue;
        }
      }
    `}</style>
    <style global jsx>{`
      body {
        background: black;
      }
    `}</style>
  </div>
)
```

Save it, start next, change some prop on the CSS, you'll get this:
![image](https://user-images.githubusercontent.com/3399236/39451353-c84560ac-4ca4-11e8-8a0f-526b02f501d2.png)

You can see that i don't have anything special:
![image](https://user-images.githubusercontent.com/3399236/39451383-e40b5dd2-4ca4-11e8-8952-231667789d2f.png)

**Comment by Richtervn** [comment]
Oh please, I did a search before open #4246. I've just upgrade from next 5.1 to 6. I swear I don't have any wrong syntax or empty style jsx. I even never use React.Fragment

**Comment by bouzoumita** [comment]
you can reproduce this issue with a new project using this "dependencies": {
    "next": "^6.0.0",
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  }
and it occur in the hot reload.

**Comment by kamilml** [comment]
This is so annoying. I use style jsx for all the css code in my components. And I am getting this error every time.

**Comment by kamilml** [comment]
I fixed the error reinstalling next@5.1.0 instead 6.00

**Comment by giuseppeg** [comment]
Good news I tracked down the source of the issue to react-hot-loader v4. I'll work with the Next.js folks to fix this asap :)

**Comment by giuseppeg** [comment]
This is fixed in `next@6.0.1-canary.0` or `next@canary` if you will

**Comment by timmywil** [comment]
I'm using `next@6.0.1-canary.1` and am still getting the error [described](https://github.com/zeit/styled-jsx/issues/425#issuecomment-385535539) by @Negan1911.

**Comment by timneutkens** [comment]
@timmywil see https://github.com/zeit/next.js/issues/4299
